### PR TITLE
allow removing npm packages

### LINKED ISSUE #104: Add API for removing packages
I see that this is on your radar https://github.com/ember-cli/ember-try/pull/45#issue-128709611

> packages in package.json cannot be removed. This needs further thought and perhaps our own configuration syntax

I just came across the need for this testing ember-data back before it was an npm package. Any API thoughts?

### PR DESCRIPTION
**Pull request by kellyselden**
Resolves #104

### CODE REVIEW

**Comment by kellyselden** [comment]
rebased

**Comment by kellyselden** [comment]
passing now

**Comment by kellyselden** [comment]
Thanks.

**Comment by kategengler** [comment]
No, thank you! Been meaning to support this for a long time.

**Pull request merged**
