### PR TITLE
Allow chained commands and setting env vars in commands

### LINKED ISSUE #94: Command from config cannot include multiple command with | or &&
Currently one cannot configure to run multiple commands with one liners like:

`command: 'npm uninstall X && ember test --filter unit'`

Main issue being that commands are run with child_process.spawn and not with exec. I understand that spawn is used through out the addon but maybe there is something we could do about it?

Workaround: Move command into *.sh file and set it up to be run by ember-try.

`command: "./my-script.sh"`

### PR DESCRIPTION
**Pull request by kategengler**
- Add note to readme about needing to npm link ember-try

Allows:

`ember try:one <scenario> --- FOO=5 ember test`
`ember try:one <scenario> --- 'ember test && echo 2'` (note quotes)

The same goes for the command in the config file. 

Fixes #94 and #87

### CODE REVIEW

**Comment by kategengler** [comment]
@rwjblue See https://github.com/ember-cli/ember-try/pull/97 re: appveyor. Plan to at least manually check windows for now.

**Comment by rwjblue** [comment]
Sounds good.

**Comment by kategengler** [comment]
Manually checked on windows: All the previous types of commands seem to work, but chained commands do not.

**Comment by kategengler** [comment]
Gah, not working on linux either. Works on mac, sigh.

**Comment by kellyselden** [comment]
`FOO=5 ember test` is invalid syntax on Windows. I've always used `cross-env` for setting env vars multi-platform. ([here for example](https://github.com/kategengler/ember-cli-code-coverage#usage))

**Comment by kategengler** [comment]
@kellyselden `cross-env` probably works already, since it's a command. Part of this work was to allow setting environment variables in the command passed to ember-try. The later part, which should be possible, isn't working on windows (chained commands with && or ||), though it might be the same issue as what I'm seeing on linux: When all-commands.sh is run, the commands use the ember-try included with ember-cli, rather than the working copy.

**Pull request merged**
